project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "slides/*.qmd" 
  resources:
    - "book/"
    - "slides/" 

website:
  title: "Intro to DH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - text: Book
        href: book/index.qmd


  sidebar:
    - title: "Book"
      style: "docked"
      search: true
      contents:
        - book/index.qmd
        - book/01-introduction.qmd
        - book/02-R.qmd


bibliography: book/references.bib

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    toc-location: right
    toc-title: "On this page"
    number-sections: true
    number-depth: 3
    code-link: true
    code-tools: 
      source: false
      toggle: true
    highlight-style: github
  revealjs:
    theme: default
    reveal_plugins:
      - notes
      - search
      - zoom

include-after-body: 
     - file: _footer.html