project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!_*.qmd"
    - "book/slides/*.qmd"
  resources:
    - "book/"

website:
  title: "Intro to DH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: toolbox.qmd
        text: Toybox
      - text: Book
        href: book/index.qmd
      - text: Quiz
        href: exam.qmd
        


  sidebar:
    - title: "Book"
      style: "docked"
      search: true
      contents:
        - book/index.qmd
        - book/01-introduction.qmd
        - book/02-R.qmd
        - book/03-dice.qmd
        - book/04-cards.qmd
        - book/05-tidyverse.qmd
        - book/06-qta.qmd


bibliography: book/references.bib

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    toc-location: right
    toc-title: "On this page"
    number-sections: true
    number-depth: 3
    code-link: true
    code-tools: 
      source: false
      toggle: true
    highlight-style: github
    include-after-body:
      - file: _footer.html
    filter:
      - book/collapse-callout.lua
  revealjs:
    theme: default
    css: "../../custom.css"
    reveal_plugins:
      - notes
      - search
      - zoom
    output-dir: _site/book/slides


execute:
  freeze: auto
